export default {
  BASIC_ACTION: "BASIC_ACTION",
  GET_STUFF: "GET_STUFF",
  GOT_STUFF: "GOT_STUFF",
  GOT_NO_STUFF: "GOT_NO_STUFF",
  GET_SEARCH: "GET_SEARCH",
  GOT_SEARCH: "GOT_SEARCH",
  GET_ARTIST: "GET ARTIST",
  GOT_ARTIST: "GOT_ARTIST"
};
